include: package:flutter_lints/flutter.yaml

linter:
  rules:
    ## Error Rules
    - always_use_package_imports
    ## Style rules
    - directives_ordering
    - eol_at_end_of_file
    - file_names
    - flutter_style_todos
    - library_names
    - library_prefixes
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_null_aware_method_calls
    - prefer_single_quotes
    - sort_constructors_first
    - sort_unnamed_constructors_first
    ## Pub rules
    - sort_pub_dependencies
